-- phpMyAdmin SQL Dump
-- version 5.1.2
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: May 27, 2023 at 01:56 PM
-- Server version: 5.7.24
-- PHP Version: 8.0.1

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `otr_authen`
--

-- --------------------------------------------------------

--
-- Table structure for table `review`
--

CREATE TABLE `review` (
  `id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `review`
--

INSERT INTO `review` (`id`, `name`, `email`, `message`, `created_at`) VALUES
(1, 'User Test', 'user123@gmail.com', '        Bangkok was a great city for traveller who loves a beautiful southeast asia culture and arts coming with mouthwatering street food that represent their country. A Checklist for every traveller that need to visit!!', '2023-05-26 18:43:47');

-- --------------------------------------------------------

--
-- Table structure for table `travel`
--

CREATE TABLE `travel` (
  `id` int(11) NOT NULL,
  `Country` varchar(255) NOT NULL,
  `City` varchar(255) NOT NULL,
  `Label` text NOT NULL,
  `Content` varchar(10000) NOT NULL,
  `image_file` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `travel`
--

INSERT INTO `travel` (`id`, `Country`, `City`, `Label`, `Content`, `image_file`) VALUES
(1, 'Thailand', 'Bangkok', 'Climate', 'According to the World Meteorological Organization (WMO), Bangkok is one of the hottest cities in the world. Located just 14 degrees north of the Equator, Bangkok is warm at any time of the year with temperatures over 30°C (86°F).\r\n\r\nThe most pleasant time to visit is the cool season that lasts from November till February. It is both the coolest and driest period — the Emerald Buddha statue in Wat Phra Kaew even wears a scarf during this period! Don\'t think that\'s necessary though — daytime temperatures still hover around 32°C (89.6°F), but it does cool down into the lower 20\'s as it gets dark (lower 70\'s °F). March and April represent the hot season, and hot it is — 35°C (95°F) on average, but don\'t be surprised to see temperatures rising towards 40 degrees Celsius (around 100°F+). This is the worst season to visit Bangkok, so plan a lot of air-conditioned shopping mall visits and get a hotel with a swimming pool. Then there\'s the wet season that runs from May till October. Expect massive downpours resulting in floods all over the city, and spells of thunder at times. It\'s not all bad though — the afternoon showers are actually a pleasant way to cool down from the heat, and while they may last all day, usually they\'re over within an hour. Extreme rainfall happens in September and October, so these months are best avoided.', 'bangkok_climate.jpg'),
(2, 'Thailand', 'Bangkok', 'Food', 'Khao Niew Mamuang (mango with sticky rice)\r\n\r\nSpeaking of mangoes, make your first stop in Bangkok to absolutely anywhere where you can get your mitts on some khao niew mamuang – aka mango sticky rice.\r\n\r\nThis is a sweet dish, consisting of coconut milk cooked slowly with a mixture of sugar and salt. The concoction is poured over some freshly prepared sticky rice, and once it’s settled, slices of ripe, peeled mango are placed on top.', 'bangkok_food1.jpg'),
(3, 'Thailand', 'Bangkok', 'Food', 'Kuay Teow Reua (pork noodle soup)\r\n\r\nKuay Teow Reua is a noodle soup dish made with pork. The broth is infused with the classic Thai blend of garlic and chillies, though the exact recipe will depend on where you go, and can often be customised.\r\n\r\nThis is a traditional Thai dish, so there’s bound to be a bit of variation – it actually used to be served on boats, which is why it’s more commonly known as Boat Noodles.', 'bangkok_food2.jpg'),
(4, 'Thailand', 'Bangkok', 'Places', 'Wat Pho: The Famous Temple Of The Reclining Buddha\r\n\r\nAmongst the best Bangkok tourist attractions, located behind the Temple of the Emerald Buddha, this temple is one of the best place in Bangkok irrespective of whether you’re religious at heart or not because this is also a great place to get a good Thai massage. Apart from that, it is one of the largest temple complexes in the city wherein a giant reclining Buddha measures 46 meters long, is all covered in gold leaf, and offers a relaxing ambience. Touring this place is one of the best things to do in Bangkok with family. ', 'bangkok_places1.jpg'),
(5, 'Thailand', 'Bangkok', 'Places', 'Giant Swing: A Striking Attraction\r\n\r\nThis is an interesting spot on the Bangkok attractions map. It denotes and highlights a rich church with clearing rooftop, wonderful divider paintings and stunning hand-cut teak wood entry panels. Situated at a height of 21m between WatSuthat and Bangkok City Hall. The Giant Swing’s two towering red columns can be visible from afar. If you’re looking for places to visit in Bangkok in 2 days then this place is a must-have on your itinerary list.', 'bangkok_places2.jpg'),
(6, 'Thailand', 'Bangkok', 'Suggestion', 'Don’t ever touch the Thai people’s head\r\n\r\nThai peoples’ head is an important part of their body and a sense of pride. It is not only considered rude to touch a stranger’s head in Thailand but it also makes an individual feel insulted. It also includes a head of a statue, especially the Buddha statue. So why to make anybody feel insulted while we are on an enjoying journey. Instead save your head from getting a blow by avoiding touching a Thai head.\r\n\r\nHowever, close friends and family elders do touch the heads of the younger and kids as an expression of love or friendship.\r\n', 'bangkok_suggest.jpg'),
(7, 'Japan', 'Tokyo', 'Climate', 'Tokyo is classified as lying in the humid subtropical climate zone and has four distinct seasons. Summers are usually hot and humid with a temperature range of about 20-30°C (68-86°F), though it can sometimes climb into the high thirties. Winters are usually cold but not unbearable, with temperatures generally ranging from 0-10°C (32-50°F), though occasional cold spells can send temperatures plummeting below zero at night. Snow is rare, but on those rare occasions (once every few years) when Tokyo is hit by a snowstorm, much of the train network grinds to a halt. The famous cherry blossoms bloom in March-April and parks, most famously Ueno, fill up with blue tarps and sozzled salarymen.', 'tokyo_climate.jpg'),
(8, 'Japan', 'Tokyo', 'Food', 'Nigiri-zushi\r\nThe most popular type of sushi today, nigiri-zushi originated as a fast-food dish in Tokyo. Consisting of a piece of seafood put onto a small ball of rice, it takes much less time and effort to prepare than more traditional sushi dishes. Nigiri-zushi are served at all sushi restaurants from inexpensive conveyor belt sushi to Michelin-starred restaurants. The Tsukiji Outer Market is one of the best places to eat fresh sushi.', 'tokyo_food1.jpg'),
(9, 'Japan', 'Tokyo', 'Food', 'Tempura\r\nAnother of Japan\'s most famous dishes, tempura also underwent major development in the capital city. Before the Edo Period, mainly vegetables were used for tempura, but Edo cooks started to deep fry seafood from Edo Bay in tempura batter, resulting in the more varied dish we know today. A visit to a specialized tempura restaurant (tempura-ya) is the recommended way to enjoy tempura.', 'tokyo_food2.jpg'),
(10, 'Japan', 'Tokyo', 'Places', 'Sensoji (also known as Asakusa Kannon Temple) is a Buddhist temple located in Asakusa. It is one of Tokyo most colorful and popular temples.The legend says that in the year 628, two brothers fished a statue of Kannon, the goddess of mercy, out of the Sumida River, and even though they put the statue back into the river, it always returned to them. Consequently, Sensoji was built nearby for the goddess of Kannon. The temple was completed in 645, making it Tokyo oldest temple.', 'tokyo_places1.jpg'),
(11, 'Japan', 'Tokyo', 'Places', 'Ueno Park is a large public park next to Ueno Station in central Tokyo. The park grounds were originally part of Kaneiji Temple, which used to be one of the city\'s largest and wealthiest temples and a family temple of the ruling Tokugawa clan during the Edo Period. Kaneiji stood in the northeast of the capital to protect the city from evil, much like Enryakuji Temple in Kyoto.\r\n\r\nDuring the Boshin Civil War, which followed the Meiji Restoration in 1868, Kaneiji suffered nearly complete destruction in a battle between the victorious forces of the new Meiji government and loyalists of the overthrown shogunate. After the battle, the temple grounds were converted into one of Japan\'s first Western-style parks and opened to the public in 1873. A statue of Saigo Takamori, one of the generals in the Battle of Ueno, stands near the park\'s southern entrance.', 'tokyo_places2.jpg'),
(12, 'Japan', 'Tokyo', 'Suggestion', 'Don\'t take small children on the subway at rush hour\r\nIt gets very, very crowded\r\n\r\nThe subway is the main mode of public transport in Tokyo, especially for office workers. During rush hours, the trains can get incredibly packed, to such an extent that the train staff will give people a little push to get them inside the carriage.\r\n\r\nWhile it’s fine for adults to join the throng, it’s not advised to take small children on the subway from 8 am to 9 am and from 5 pm to 6 pm during weekdays. This is less a point of etiquette and more one of basic safety. Take a cab or wait an hour for the crowds to subside.', 'tokyo_suggest.jpeg'),
(13, 'France', 'Paris', 'Climate', 'Being located in Western Europe, Paris has a maritime climate with cool winters and warm summers. The moderating effect of the Atlantic Ocean helps to temper temperature extremes in much of western Europe, including France. Even in January, the coldest month, temperatures nearly always exceed the freezing point with an average high of 7°C (45°F). Snow is not common in Paris, although it will fall a few times a year. Most of Paris\' precipitation comes in the form of light rain year-round.\r\n\r\nSummers in Paris are warm and humid, with an average high of 25°C (77°F) during the mid-summer months. Occasional heat waves can push temperatures above 35°C (95°F).\r\n\r\nSpring and fall are normally cool and wet. Spring in Paris is largely unstable, with temperatures ranging from pleasant to quite cold. Short snowfalls can even occur in March. There\'s even a saying \"En avril, ne te decouvre pas d\'un fil,\" which means, \"In April, don\'t take off even a thread.\" It can still be chilly, with unpredictable gusts and showers. By May, a true thaw is underway, to the delight of all. Still, it can be an extraordinarily rainy month.\r\n\r\nWhat to Pack: March brings a slight thaw, but not enough to go sleeveless. You\'ll still need plenty of warm sweaters, plus waterproof shoes and a jacket. Pack layers, and make sure to keep those waterproof clothes and shoes on hand.', 'paris_climate.jpg'),
(14, 'France', 'Paris', 'Food', 'Escargots: A national symbol\r\nYou just can’t leave Paris without trying them!\r\n\r\nThough we enjoy snails cooked in a variety of ways in Paris, the Burgundy recipe remains the most popular. The escargots (usually a dozen of them) are presented in their shells and stuffed with a mouthwatering combination of garlic, herbs and butter.\r\n\r\nHowever, escargots are now so popular that countless Paris restaurants have put their own creative spin on the dish. You’ll now find snails served with Roquefort, truffle, and even curry-based sauces, and so much more.\r\n\r\nWant to know the best part? Not only are escargots delicious, but they’re also rich in iron and magnesium.\r\n', 'paris_food1.jpeg'),
(15, 'France', 'Paris', 'Food', 'Onion soup \r\nAnother famous food in Paris, onion soup is about as comforting as it gets. According to legend, the recipe was invented by Louis XV nearly three centuries ago. Nowadays, the caramelized onion and beef broth is served gratinéed with crusty croutons and a slice of Gruyère cheese on top. And, oui bien sûr, it tastes as good as it sounds. The preparation of traditional French onion soup is as simple as it gets, and a testament to how seriously we take our gastronomy here in France. What other place on earth could take the humble onion and elevate it to such culinary heights?', 'paris_food2.jpg'),
(16, 'France', 'Paris', 'Places', 'Notre Dame Cathedral\r\nOne of the most enduring symbols of Paris: Notre-Dame de Paris, also known as Notre Dame, a Roman Catholic cathedral is located on the eastern half of the Ile de la Cité. It is widely considered one of the finest examples of French Gothic architecture in France and Europe. Begun in 1163 and completed in 1345, this cathedral is a sight with its portals surrounded by his many sculptures and gargoyles that adorn the roof.\r\n\r\nWe advise you to walk around the cathedral, then go inside and climb the 387 steps to the top of the towers. The climb to the top of the towers can be exhausting, but you will get a panoramic view of the region and see the famous gargoyles up close.', 'paris_places1.jpeg'),
(17, 'France', 'Paris', 'Places', 'The Latin Quarter - Luxembourg park\r\nThe Latin Quarter of Paris is located on the left bank of the Seine, around the Sorbonne. Known for its student life, lively atmosphere and bistros, the Latin Quarter is the home to many higher education institutions, such as the Ecole Normale Superieure, the Ecole des Mines de Paris or the Ecole Polytechnique. The area takes its name from the Latin language, which was once widespread in and around the University since Latin was the international language of learning in the Middle Ages. The Luxembourg park is a private garden open to the public created in 1612 at the request of Marie de Medicis to accompany the Luxembourg Palace. The Parisians affectionately call it the \"Luco\". The garden surrounds the Palais du Luxembourg, where the Senate seats. Redesigned by André Le Nôtre, it is very pleasant to walk around; you will also find an orchard, several varieties of apples, an apiary and a greenhouse with orchid collection. There are 106 statues, a bronze reduction of the Statue of Liberty and 3 beautiful fountains.', 'paris_places2.jpg'),
(18, 'France', 'Paris', 'Suggestion', 'Eating At Restaurants Near Famous Places\r\nOne of the big mistakes to avoid in Paris is eating at restaurants near famous places as they’re usually way more expensive than any other restaurants in the city.\r\n\r\nFor example, a restaurant next to the Sacré Coeur is likely to be more expensive than one on a non-famous street in Paris. Also, restaurants with Eiffel Tower views are more likely to be more expensive compared to the others.\r\n\r\nWhere to eat instead?\r\n\r\nParis has a number of restaurants in that you can never fail to find one at any turn you make.\r\n\r\nSo try to look for ones that are a bit far from the popular site as you’ll get a better value for your money – and a bigger portion as well.', 'paris_suggest.jpg'),
(19, 'Spain', 'Barcelona', 'Climate', 'The city of Barcelona has a classic \"Mediterranean climate\" with mild, humid winters and hot, dry summers. While there are four distinct seasons to the year, they are not at all of equal length if measured by conditions rather than equinoxes: \"summer\" lasts from May till October (half the year), cooler winter temperatures continue for three months, (December, January and February), and the transitional periods of spring and fall are only represented by the single months of April and November.', 'barcelona_climate.jpg'),
(20, 'Spain', 'Barcelona', 'Food', 'If you are visiting Catalonia, you will have a chance to eat calçots. So what exactly are they? Calçot is a crossover species of spring onion and leek – and it really looks like a mixture of the two. Calçots are seasonal so you can only have them between November and March. The best way to enjoy calçots is in a winter barbecue style with romesco sauce – which is called Calçotada. Most of the time you have to travel to the countryside of Barcelona to eat it but if you want to try it in the city center try them at l’Antic Forn.', 'barcelona_food1.jpg'),
(21, 'Spain', 'Barcelona', 'Food', 'Paella is an extremely popular dish in Spain, it was created when Arabs showed Valencians how to cook rice perfectly with saffron and Valencians combined it with their pans and seafood.  It requires some cooking expertise to make it as it can often come out bland and taste a bit metallic-y.  Despite its origin from Valencia you can enjoy this dish in different regions of Spain, especially those by the sea and Barcelona is somewhere to try it!  Can Majo is a restaurant which happens to offer a huge variety of seafood mixtures and rice dishes – so their paella is a must eat while in the city!', 'barcelona_food2.jpg'),
(22, 'Spain', 'Barcelona', 'Places', 'Casa Batlló\r\nCasa Batlló show famous Catalan architect Antoni Gaudí at his best. Of all the Gaudí apartments in Barcelona, this is probably the most recognized (it\'s also a UNESCO World Heritage site). Sitting down the street from Casa Milà, Casa Batlló is known for its vibrant colors, intricate tile work and skeletal terraces. The unconventional façade is inspired by the legend of St. George, whose story is famous for slaying a dragon to save the princess. The roof in particular depicts the dragon\'s scaly back while the skeletal balconies and boney windows are said to represent the dragon\'s previous victims (the legend goes that someone would be sacrificed every day so the dragon wouldn\'t take the whole town). After you\'ve taken the time to absorb the monstrous amount of detail used on the outside of the building, stop inside to tour the equally eye-catching interiors, including the Noble Floor, which was once home to the Batlló family. With your ticket, you\'re also able to access the roof to check out Gaudí\'s admirable mosaic work up close, including those on the dragon\'s back and the roof\'s many colorful chimneys. ', 'barcelona_places1.jpg'),
(23, 'Spain', 'Barcelona', 'Places', 'Camp Nou Stadium\r\nEven if you are not a football fan, Camp Nou is worth a visit to experience the pride Catalans have for the FC Barcelona team. Able to hold nearly 100,000 screaming fans, which can be quite intimidating for visiting teams, Camp Nou is the largest stadium in Europe. The on-site museum showcases trophies and awards the team has garnered through the years. Interesting and interactive displays invite visitors to learn a little more about the fútbol culture and its impact on the city.  For example, Catalans rallied behind the motto \"més que un club\" (more than a club) during the oppressive Francisco Franco regime, becoming a symbol of striving for independence. The slogan is even spelled out in giant gold letters among the royal and ruby stadium seats. Depending on which team they are playing, tickets to a game can be expensive (especially for El Classico). However, visitors note that seeing the dedicated fans and watching some of the best soccer players in the world in action is a once-in-a-lifetime experience. ', 'barcelona_places2.jpg'),
(24, 'Spain', 'Barcelona', 'Suggestion', 'Drink beer out of huge glasses\r\n\r\nAs a rule of thumb, the Catalans drink less than some of their other European neighbours, and public drunkenness is less common. If this is obviously a question of personal choice and public culture, the fact that the locals tend to drink smaller measures of alcohol doubtless helps. The average Catalan doesn’t drink a pint of beer, but a caña, a small glass. Wine is also usually served in small measures.', 'barcelona_suggest.jpg'),
(25, 'England', 'London', 'Climate', 'Despite varied weather patterns, the city has an unfair reputation for being drizzly, grey and rainy. This is mostly an unfounded belief. In fact, London enjoys a drier climate than the rest of United Kingdom (and a warmer one) due to it having its own urban microclimate. On average, only one in three days will bring rain and usually then only for a short period. In some cases, 2010 being a well-known example, the city can go without rain for several weeks, leading to hosepipe bans across the city.\r\n\r\nAs for temperatures, London is far milder than nearby continental European cities due to the presence of the Gulf Stream. The average daily maximum is 8°C (46°F) in December and January (a full 4 degrees warmer than the rest of the United Kingdom on long-term average) and February is usually the coldest month of the year. In summer, temperatures can rise up to 24°C (75°F), and once reached as high as 38°C (100°F), as happened in 2003.\r\n\r\nDue to the urban microclimate, inner London can feel hot and humid for several days in the summer months, especially during the evenings. However, summer is still perhaps the best season for tourists as it has long daylight hours as well as mostly mild temperatures.', 'london_climate.jpg'),
(26, 'England', 'London', 'Food', 'Full English Breakfast \r\n\r\nA culinary relic of our Anglo-Saxon roots, this dish became popular among all socioeconomic classes during the Industrial Revolution. It’s a cuddle on a plate, perfect for the morning after a big night out or to set you up for a long day of work. Head to a classic “caff” and go for the full works: sausage, bacon, baked beans, tomato, fried egg, fried slice and of course, a hefty slice of black pudding.', 'london_food1.jpg'),
(27, 'England', 'London', 'Food', 'Fish and Chips \r\nThe history of fish and chips reveals a surprising origin story. Fried fish came from the Jews exiled from the Iberian Peninsula during the 1400s, and chips from French-speaking Belgians. The only thing we did was pair them together for the first time. But they became such an important part of the national psyche that they were one of the few things not rationed during World War II. The best place for this dish? An actual fish and chip shop—not a pub!', 'london_food2.jpg'),
(28, 'England', 'London', 'Places', 'Warner Bros. Studio Tour London\r\n\r\nHave a magical day out with a behind-the-scenes tour of the Harry Potter films at Warner Bros. Studio Tour London The Making of Harry Potter. See first-hand the sets, costumes and props used in all the Harry Potter films, and step inside some of the films\' locations, including the Great Hall, Dumbledore\'s office and Hagrid\'s hut. It\'s the ultimate Harry Potter experience!', 'london_places1.jpg'),
(29, 'England', 'London', 'Places', 'Westminster Abbey\r\n\r\nOne of London\'s most important UNESCO World Heritage Sites, Westminster Abbey plays host to many special ceremonies including coronations and royal weddings. Marvel at the impressive architecture, see the resting places of kings and queens passed and visit poets corner where some of the UK\'s most famous writers, such as William Shakespeare and Jane Austen, are buried.', 'london_places2.jpg'),
(30, 'England', 'London', 'Suggestion', 'DON’T try to use cash on TFL buses\r\n\r\nWhile you can use cash to board Golden Tours Hop-on Hop-off buses, Transport for London buses have not accepted cash since July 2014. If you want to use a London bus, you’ll need an Oyster Card (available from ticket desks at London underground stations) or you can use contactless payment if you have a card issued in the UK (some internationally issued contactless cards will work, others won’t – so to be sure, go with Oyster).', 'london_suggest.jpg'),
(31, 'Netherlands', 'Amsterdam', 'Climate', 'Amsterdam is a large city and a major tourist destination, so you can visit it all year round. However, in winter the days are short (8 hours daylight around Christmas), and the weather may be too cold to walk around the city comfortably, let alone cycle. January and February are the coldest months, with lows around -1°C and highs around 5°C. July and August are the warmest months, with an average temperature of 22°C (72°F). Some things are seasonal: the tulip fields flower only in the spring, and as of 2014, after the abdication of Queen Beatrix on 30 April 2013, King\'s Day (Koningsdag) is, unless it falls on a Sunday, on 27 April, the birthday of King Willem-Alexander. If the 27 April is on Sunday, the birthday of the king is celebrated on 26 April.', 'amsterdam_climate.jpg'),
(32, 'Netherlands', 'Amsterdam', 'Food', 'Bitterballen\r\n\r\nIn Amsterdam, crispy meatballs called Bitterballen are the go-to snack at bars around the city. Since most travelers visit at least one bar in Amsterdam, eating Bitterballen is almost inevitable when visiting the DAM. But, you may be wondering, what are Bitterballen?\r\n\r\nThe Bitterballen recipe is fairly straightforward and can be completed in a few steps. First, Dutch chefs slow cook meat and refrigerate the resulting stew until it solidifies. They then form the meat mixture into little balls, bread them and fry them to crispy perfection.\r\n\r\nEaters get the better end of the stick, or in this case ball. Plan to eat Bitterballen with your fingers, dipping each round nugget into spicy mustard before popping it into your mouth. Just be careful not to burn your tongue.', 'amsterdam_food1.jpg'),
(33, 'Netherlands', 'Amsterdam', 'Food', 'Broodje Haring (Herring Sandwich)\r\n\r\nIf Bitterballen is the most popular bar food in Amsterdam, then pickled herring sandwiches win the prize when it comes to street food. Locals stop at fish stands called haringhandel to order herring sandwiches called broodjes haring all year long but especially in the summer when it’s herring season.\r\n\r\nOrder your broodje haring with pickles and onions. If you don’t like bread, you can eat chunks of herring with toothpicks. If you don’t like herring, then order smoked eel. Whatever you order, don’t forget the pickles and onions.\r\n\r\n', 'amsterdam_food2.jpg'),
(34, 'Netherlands', 'Amsterdam', 'Places', 'Rijksmuseum – Journey Back In The 19th Century\r\n\r\nOne of the most popular Amsterdam visiting places for art fanatics, this Museum goes back to 1809 when it was built to house the brilliant art and antiques of the nation in more than 250 rooms. There is also a huge library with an extensive collection of more than 35,000 books and manuscripts. Traditional handicrafts, medieval sculptures, and modern art styles are also on display here. You can hire an Amsterdam tourist guide or take a language-guided tour of this museum.', 'amsterdam_places1.png'),
(35, 'Netherlands', 'Amsterdam', 'Places', 'Begijnhof – For A Peaceful Stroll\r\n\r\nIf you are looking for some calm and serenity, this is one of the best places to visit in Amsterdam. It is one of the oldest hofjes and is primarily a group of historic buildings. It was originally a Béguinage and in present times is the site of two churches, the Catholic Houten Huys and the English Reformed Church. It has a secluded garden where one can enjoy a peaceful time a well as wondrous Mondrian-designed pulpit panels. It is one of the most stunning visiting places in Amsterdam. ', 'amsterdam_places2.jpg'),
(36, 'Netherlands', 'Amsterdam', 'Suggestion', 'Don’t Confuse Coffee Shops for a Starbucks\r\n\r\nAmsterdam is famous for its coffee shops, but don’t mistake these for cafes. If you want a cappuccino, find a sidewalk cafe to get your caffeine fix. The so-called coffee shops are for a fix of another kind. For those who don’t know, cannabis, hash and other soft drugs are tolerated in these establishments. They don’t sell alcohol, but some have food on the menu (and not just brownies). There are about 200 coffee shops in the city, and while they’re not allowed to advertise, it’s not hard to identify and locate one. Look for a green and white license sticker in the window. Be aware, the herbs might be more potent here than you’re used to, so go easy on the stuff.', 'amsterdam_suggest.jpg'),
(37, 'Turkey ', 'Istanbul', 'Climate', 'Istanbul has a temperate oceanic climate which is influenced by a continental climate, with hot and humid summers and cold, wet and occasionally snowy winters.\r\n\r\nIstanbul has a high annual average rainfall of 844mm (which is more than that of London, Dublin or Brussels, whose negative reputation Istanbul does not suffer), with late autumn and winter being the wettest, and late spring and summer being the driest. Although late spring and summer are relatively dry when compared to the other seasons, rainfall is significant during these seasons, and there is no dry season as a result.\r\n\r\nIf there is a negative reputation that Istanbul does suffer from, it is the high annual relative humidity, especially during winter and summer with the accompanying wind chill and concrete-island effect during each respective season.\r\n\r\nSummer is generally hot with averages around 27ºC during the day and 18ºC at night. High relative humidity levels and the ‘concrete-island effect’ only make things worse. Expect temperatures of up to 35° C for the hottest days of the year. Summer is also the driest season, but it does infrequently rain. Showers tend to last for 15-30 minutes with the sun usually reappearing again on the same day. Flash floods are a common occurrence after heavy rainfalls (especially during summer), due to the city\'s hilly topography and inadequate sewage systems.\r\n\r\nFor visitors an umbrella is recommended during spring, autumn and winter, and during the summer to avoid the sun and occasionally the rain. However, it’s not such a big problem, since streets of Istanbul are suddenly filled by umbrella sellers as soon as it starts raining. Although the umbrellas they provide are a little shoddy, going rate is only TRY5 –about USD3- per umbrella (though you can find much better umbrellas for that price at shops if you look around a bit).', 'istanbul_climate.jpg'),
(38, 'Turkey ', 'Istanbul', 'Food', 'Islak Burger\r\n\r\nAlthough the name islak burger literally translates as “wet burger,” it’s much more appetizing than it sounds – we promise! These unusual burgers get their name because they’re steamed, making them soft, juicy, and incredibly rich.\r\n\r\nEach islak burger is made of a delicious beef patty tucked inside a soft white hamburger bun. The inside and outside of the bun are soaked in a flavor-packed garlic and tomato sauce before the whole thing is nestled inside a steam box. This keeps every burger soft and warm until it’s ready to eat.  ', 'istanbul_food1.jpg'),
(39, 'Turkey ', 'Istanbul', 'Food', 'Menemen\r\n\r\nIf a traditional Turkish breakfast is way too much for you, dig into a plate of menemen for your first meal of the day instead. A creative and delectable type of scrambled eggs, menemen is made up of lightly beaten eggs that are cooked in a skillet with onions, peppers, tomatoes, and mixed herbs. To give it an extra kick, fresh or dried chilies are sometimes added, too.\r\n\r\nAll the different ingredients give this dish absolutely loads of amazing flavor and a fantastic texture. Enjoy it along with some freshly-baked bread and a cup of Turkish coffee, and you’ll be set for the day!', 'istanbul_food2.jpg'),
(40, 'Turkey ', 'Istanbul', 'Places', 'Stroll the Hippodrome\r\n\r\nThe ancient Hippodrome was begun by Septimius Severus in CE 203 and completed by Constantine the Great in CE 330.\r\n\r\nThis was the center of Byzantine public life and the scene of splendid games and chariot races but also factional conflicts.\r\n\r\nToday, there isn\'t much of the Hippodrome left to see, except for a small section of the gallery walls on the southern side, but the At Meydanı (park), which now stands on the site is home to a variety of monuments.\r\n\r\nOn the northwest side is a fountain, presented to the Ottoman sultan by the German Emperor William II in 1898.\r\n\r\nThen, heading southwest are three ancient monuments: a 20-meter high Egyptian obelisk (from Heliopolis); the Serpent Column brought here from Delphi by Constantine; and a stone obelisk that originally was clad in gold-covered bronze plating until they were stolen by the soldiers of the 4th Crusade in 1204.', 'istanbul_places1.jpg'),
(41, 'Turkey ', 'Istanbul', 'Places', 'the Grand Bazaar (Kapalı Çarşı)\r\n\r\nFor many visitors, sightseeing in Istanbul is as much about shopping as museums and monumental attractions, and the Grand Bazaar is where everyone comes.\r\n\r\nThis massive covered market is basically the world\'s first shopping mall, taking up a whole city quarter, surrounded by thick walls, between the Nuruosmanıye Mosque and Beyazıt Mosque.\r\n\r\nThe Beyazıt Mosque (built in 1498-1505) itself occupies the site of Theodosius I\'s Forum and has architecture inspired by the Hagia Sophia.\r\n\r\nEntrance to the bazaar is through one of 11 gates from where a maze of vaulted-ceiling laneways, lined by shops and stalls selling every Turkish souvenir and handicraft you could imagine, cover the area.\r\n\r\nThe various trades are still mostly segregated into particular sections, which makes browsing easier.\r\n\r\nNear the bazaar\'s Divanyolu Caddesi entrance is the Burned Column. This stump (still 40 meters high) of a porphyry column was set up by Constantine the Great in his forum. Until 1105, it bore a bronze statue of Constantine.', 'istanbul_places2.jpg'),
(42, 'Turkey ', 'Istanbul', 'Suggestion', 'Drinking the tap water\r\n\r\nAlthough there is no official advice against drinking tap water in Istanbul, we don’t recommend doing so. Most locals stick to bottled or filtered water, which is usually enough to indicate that you should follow suit.\r\n\r\nIt’s not like water in places like India or Cambodia, though. The risk here isn’t really of serious illnesses. It’s all mainly down to taste. Istanbul’s aqua isn’t palatable because of the chemicals used to treat it. You don’t need to worry about using it to brush your teeth or cooking – the water is said to be okay for small tasks like that.', 'istanbul_suggest.jpg'),
(43, 'Italy', 'Rome', 'Climate', 'Spring is a relatively mild and rainy season. The temperatures remain cool until mid-April. In May the first warmer days arrive but the seabreeze keeps it cool.\r\n\r\nSummer, from June to August, is hot and sunny. Clear days are the norm especially in July and August. On hot days the temperature touches easily 34/35 °C, and every year it reaches for a few days 37/38 °C. It goes better on the Roman coast, where the daytime temperature can be a few degrees lower than in the city center.\r\n\r\nAutumn, from September to November, is mild and humid, with sunny days alternating with periods of cloudy skies and rain, which gradually becomes more frequent. There\'s no shortage of sunny days, at least in the first part; in October the nice and almost summer-like days are frequent especially in the first half of the month. In November, the rains are frequent and the temperature decreases fairly rapidly: at the beginning of the month the temperature is often very mild, while at the end of the month, the weather is often similar to that of winter.\r\n\r\nWinter, from December to February, is quite mild, given that the average temperature in January is about 7.5 °C. There\'s no shortage of sunny days, which can be mild, but it often gets cold at night, with lows around freezing or slightly above. Cloudy periods, accompanied by wind and rain, are milder, especially at night, because of the wind from the south, and cloud cover which is able to prevent nocturnal cooling. In early December, an autumn-like weather can still prevail, and abundant rainfall. In the second half of February, in some years you can already see the first spring-like days.', 'rome_climate.jpg'),
(44, 'Italy', 'Rome', 'Food', 'Rigatoni Carbonara\r\n\r\nTrue Roman Carbonara is an art form. Impossibly creamy (with not a spot of cream in sight), this rich Roman sauce is one of those dishes you dream about for years to come. In my humble opinion, rigatoni carbonara is a must try food in Rome.\r\n\r\nI figured carbonara was a long time Roman classic -- but soon found out that is not the case! Most Romans hadn\'t heard of Carbonara until the 1950s or so, and one (unlikely) origin story even says that the dish could have been invented from the American GI\'s rations of bacon and eggs during World War II (though most likely it came from coal miners, carbonai, who had access to the ingredients in the mountains).\r\n\r\nSo what\'s in a true Roman Carbonara today? Raw eggs, Pecorino Romano and Parmigiano Reggiano cheese, and guanciale (Italian cured pork cheek). Pancetta (cured pork belly) is also acceptable, though I prefer the guanciale version. While you\'ll find a variety of kinds of pasta smothered with carbonara sauce, I think thick rigatoni al dente is the perfect partner in crime.\r\n\r\n', 'rome_food1.jpg'),
(45, 'Italy', 'Rome', 'Food', '\r\nSuppli is a Roman snack worth seeking out. You can find good suppli at just about any Roman deli or pizza takeaway spot.\r\n\r\nBut what exactly is suppli? A piping hot ball of fried deliciousness, good suppli are made with creamy rice mixed with a meat and tomato sauce, and have a gooey piece of mozzarella cheese in the center. All of this is breaded and deep-fried, resulting in a delicious snack with a cold beer.', 'rome_food2.jpg'),
(46, 'Italy', 'Rome', 'Places', 'Trevi Fountain of Rome\r\n\r\nThe most famous fountain in Rome and perhaps even the world must be the ‘Fontana di Trevi’, or Trevi Fountain. This baroque fountain, located on the Piazza di Trevi, was built in the 18th century. The landmark and monument displays the god of the sea, Neptune on his chariot. No visit or Rome sightseeing is complete without tossing a coin in the Trevi Fountain, as this means the person throwing the coin will ‘one day return to Rome Italy’.', 'rome_places1.jpg'),
(47, 'Italy', 'Rome', 'Places', 'Castel Sant’Angelo\r\n\r\nOriginally, the 2nd-century Castel Sant’Angelo, or Castle of the Holy Angel, was a mausoleum for emperor Hadrian. After archangel Michael appeared here in 590 and ended a plague, pope Pius II had a large bronze statue of the angels placed on top of the castle. The Castle of the Holy Angel was part of Rome\'s defences and offered a place where popes could shelter, as the Vatican was connected to it by a tunnel.', 'rome_places2.jpg'),
(48, 'Italy', 'Rome', 'Suggestion', 'Don’t order a cappuccino after noon\r\n\r\nThis is arguably the most famous Italian food rule: don’t order a cappuccino after noon. Cappuccinos are considered a breakfast coffee and are often consumed first thing in the morning with a sweet pastry. After lunch, the high proportion of milk is thought to impede digestion and Italians are all about digestion. It’s the reason they order black coffee and digestivi – digestive liquors – after dinner. Digestion is of utmost importance and Italians believe drinking a cappuccino on a full stomach will be too heavy. If you need a splash of milk in your coffee, a caffe macchiato is acceptable at any hour of the day (though Italians will tell you the milk interferes with the true flavor of the coffee, which is best enjoyed black).', 'rome_suggest.jpg'),
(49, 'USA', 'New York', 'Climate', 'New York City has a humid subtropical climate, experiencing all four seasons and with about 50 inches (1,200mm) of rainfall evenly distributed throughout the year. Depending on the time of the year you visit it would be optimal to know what kind of weather you should expect.\r\n\r\nWinters in NYC are chilly and damp. However due to the moderating effect of the ocean and the urban heat island, the city does have warmer temperatures when compared to other cities on the same latitude like Pittsburgh, Columbus or Indianapolis. Nighttime lows usually hover around freezing and daytime highs are usually between the low 40s and the mid 50s (5C-15C). How cold or how warm it gets though depends greatly upon the location you\'re at in the city: the northern and western parts of the metropolitan area (like The Bronx, Yonkers and Newark) are usually colder during the night while the southern - southeastern areas such as Staten Island and Long Island may have milder temperatures.\r\n\r\nSummertime is the time when most visitors arrive at NYC. The weather is generally mild with the ocean keeping the weather from being unbearably hot. Daytime highs are usually between the low 70s and the high 80s (20C-30C) and nighttime lows hover around 60F (16C). ', 'newyork_climate.jpg'),
(50, 'USA', 'New York', 'Food', '\r\nBagels weren’t invented in New York but they’re better in the big apple than anywhere else in the world. Eastern European Jews brought their bagel recipes to New York at the turn of the 20th century. Since then, bagels have become a worldwide phenomenon enjoyed by food lovers from Edinburgh to Shanghai.\r\n\r\nIn New York, bakers hand roll bagels using a special twisting and shaping method before boiling them in a mixture of water and malt syrup and then baking them to a dark, crusty brown. Many people incorrectly attribute the New York bagel’s magnificent qualities to local water, but we attribute the New York bagel’s excellence to bagel-making methods refined over a century or more.', 'newyork_food1.jpg'),
(51, 'USA', 'New York', 'Food', 'Pastrami Sandwiches\r\n\r\nPopular for over a century, pastrami sandwiches hit the worldwide zeitgeist in 1989 thanks to a memorable scene in the movie When Harry Met Sally. Today, passionate food travelers make a pilgrimage to the Lower East Side to “have what she’s having” a/k/a a hand-carved pastrami sandwich.\r\n\r\nEastern Europeans brought the Jewish deli concept from countries like Poland and Romania when they fled their homes in search of the American dream. Made with cured and smoked beef brisket, a pastrami sandwich is the classic deli item with its thin layers of pastrami piled high between two slices of seeded rye bread.', 'newyork_food2.jpg'),
(52, 'USA', 'New York', 'Places', 'Statue of Liberty\r\n\r\nAmerica\'s most iconic sight, the Statue of Liberty is at the top of every first-time visitor\'s list of things to do in New York. It was France\'s gift to America. Built in 1886, it remains a world symbol of freedom and is one of the top attractions in America.\r\n\r\nIt is one of the world\'s largest statues, standing just under 152 feet tall from the base to the torch, and weighing approximately 450,000 pounds. You can see the statue from land, with particularly good views from Battery Park, on the southern tip of Manhattan.', 'newyork_places1.jpg'),
(53, 'USA', 'New York', 'Places', 'Rockefeller Center & Top of the Rock Observation Deck\r\n\r\nWhen it comes to New York attractions, Rockefeller Center is on almost all tourists\' itineraries. This vast entertainment and shopping complex in the middle of Manhattan is home to NBC-TV and other media, but the centerpiece is the 70-story 30 Rockefeller Plaza, an Art Deco skyscraper that offers awesome views over Manhattan from the famous Top of the Rock Observation Deck.\r\n\r\nSkating on the outdoor skating rink at the base of the tower is one of the most popular things to do in winter in New York City and a fun activity for families and couples. The rink is typically open from October to April. If you aren\'t a strong skater, don\'t worry, the rink is tiny, and for many people, this is their first time on skates, so the skill level is pretty low.', 'newyork_places2.jpg'),
(54, 'USA', 'New York', 'Suggestion', 'Don’t Forget the Bike Lanes\r\n\r\nLike the sidewalks, NYC bike lanes are basically highways too. That means that pedestrians, drivers, and other cyclists should never stop in the middle of one. Taxi passengers should be head’s up near bike lanes and not pop open a car door–always look first. Or better yet, just find a clear curb lane or another safe spot to pull over.', 'newyork_suggest.jpg'),
(55, 'Portugal', 'Lisbon', 'Climate', 'Lisbon enjoys a warm climate with mild winters and very warm summers. Strongly influenced by the Gulf Stream, it is one of the mildest climates in Europe. Among all the metropolises in Europe, here are the warmest winters on the continent, with average temperatures around 15°C (59°F) during the day and 9°C (48°F) at night in the period from December to February. Snow and frost are very rare. The typical summer season lasts about six months, from May to October, with an average temperature of 25°C (77°F) during the day and 16°C (61°F) at night. Although, sometimes in November, March, and April there are temperatures above 20°C (68.0°F) with an average temperature of 18.5°C (65°F) during the day and 11.2°C (52.2°F) at night. Rain occurs mainly in winter and the summer is very dry.\r\n\r\nLisbon is very close to the ocean, which brings windy and fast-changing weather, so you\'d better bring extra outerwear or an umbrella with you, at least in winter, spring and autumn.', 'lisbon_climate.jpg'),
(56, 'Portugal', 'Lisbon', 'Food', 'Queijo Serra da Estrela\r\n\r\nCheese from Serra da Estrela is a special kind of yellow cheese that was chosen as one of the seven gastronomical wonders of Portugal. This magnificent cheese comes from Serra da Estrela, the highest mountain range in Portugal. \r\n\r\nSerra da Estrela has rich natural resources and is the home of a special breed of sheep, the Bordaleira, that produces the milk this special creamy cheese is made from. The recipe of Queijo Serra de Estrela dates back to before Christ and its production requires following rigorous rules. The cheese curd is made in a very specific way.', 'lisbon_food1.jpg'),
(57, 'Portugal', 'Lisbon', 'Food', 'Alheira de Mirandela is a special kind of sausage that’s made from garlic, breadcrumbs, and different kind of meats. It looks, smells, and almost tastes like the sausages that are made with pork. Thus, alheira de Mirandela became a staple food for the Jewish people in Portugal, helping them avoid the inquisition.\r\n\r\nToday the sausage is made with every kind of meat, including poultry, beef, and pork along with lard and fat. The sausages are smoked using oak or olive bark to give them their unique flavor.', 'lisbon_food2.jpg'),
(58, 'Portugal', 'Lisbon', 'Places', ' Aqueduto das Águas Livres\r\n\r\nBuilt to supply the capital with fresh water from the hills north of the city, the Aqueduto das Águas Livres is one of the most important engineering constructions from the 18th century. And fun fact: construction was actually funded by special levies on meat, olive oil and wine. It covers a total length of 14 kilometres from its main source in Caneças to its end at the reservoir of Mãe d’Água das Amoreiras. Fast forward to now, it belongs to the Water Museum which organises visits to the inside of the aqueduct. And the reservoir of Mãe d’Água das Amoreiras organises cultural events and temporary exhibitions.', 'lisbon_places1.jpg'),
(59, 'Portugal', 'Lisbon', 'Places', 'Igreja de São Roque was built for the Jesuits with the assistance of Filippo Terzi on the site of an earlier chapel dedicated to São Roque. Most of the single-nave structure was built between 1565 and 1573, although it was roofless for another decade. The ceiling is a wonder of sorts. The original architect had planned a vaulted roof, but in 1582 a decision was made to build a flat wooden roof, and sturdy timber from Prussia was richly painted. The paintings in the inner sacristy are worth admiring, but the main attraction is the side chapel dedicated to St John the Baptist. Notice the lavish ivory, gold and lapis lazuli, which attest to Portugal’s colonial wealth and extravagance. Built in Rome and shipped to Lisbon in 1749 after being blessed by the Pope, it took four years to reassemble, not least because of the detailed mosaic above the altar. The neighbouring museum contains items from the chapel, including Italian goldsmiths’ work, paintings and richly embroidered vestments.', 'lisbon_places2.jpg'),
(60, 'Portugal', 'Lisbon', 'Suggestion', 'Do Not Have Dinner Before 8.00p.m.\r\n\r\nWe very rarely eat dinner early. Only at very touristy restaurants will you find anyone having dinner before 8pm. Anywhere else you´ll be joining the staff for their meal, if they are opened for business at all. If you´re tired after having explored all of the 7 hills in one day, go and have a nap, freshen up, and then join the rest of the city for dinner.\r\nDo have dinner after 9.00 p.m if you´re planning to go out, otherwise you will need to kill time afterwards. Bars only start filling up after 10:30-11pm, and nightclubs are empty until around 1-2am. Do as we do: start late, eat slowly, linger around the table chatting, drink coffee and some digestifs, and make dinner part of your “night out.” If you really want to do it like the locals do, your night out should not end before 6am.', 'lisbon_suggest.jpg'),
(61, 'South Korea', 'Seoul', 'Climate', 'Seoul has a temperate climate with 4 distinct seasons that is heavily affected by the east asian monsoon season and Siberia. Winters are cold and dry and warm clothes are definitely recommended. Most of the season\'s winds blow from eastern Siberia, leading to colder temperatures than cities in the same latitude such as Niigata and Qingdao in Japan and China respectively. Most nights drop below -5°C (23°F) and days usually remain just above freezing. When strong cold waves hit the country, Seoul is usually one of the first cities that gets affected leading to temperatures sometimes below -10°C (15°F) and on extreme cases below -15°C (5°F). The most recent occasion was in January 2016, when a very strong cold wave affected a large part of Asia, the mercury in Seoul dipped to -18°C (0°F) for the first time in 15 years. The lowest recorded temperature is -22°C (-8°F). Precipitation is usually limited to around 60-70 milimeters each year (2.5-3 inches) and most of it falls as snow.\r\n\r\nSpring and fall are by far the best times to visit since the city doesn\'t have neither too warm nor too cold temperatures. Just keep in mind that March and November still have chilly nights and that September falls in the Asian Typhoon Season.', 'seoul_climate.jpg'),
(62, 'South Korea', 'Seoul', 'Food', 'Patbingsoo (Korean Shaved Ice)\r\n\r\nShaved ice is not a unique thing, but in South Korea, they just seem to taste so much better. In Patbingsoo, the ice used is not just any plain shaved ice made from water, it’s actually made from milk! The ice is shaved so thin that it feels like you are eating milk-flavored (clean) snow. Usually, Patbingsoo is served with red beans and rice cake as pictured above, or powdered sesame seeds and rice cake.\r\n\r\n', 'seoul_food1.jpg'),
(63, 'South Korea', 'Seoul', 'Food', 'Korean Stuffed Rice Roll (Kimbap)\r\n\r\nWanna know the first thing I did when I landed in Seoul? I looked for Kimbap. Kimbap is a very comforting Korean snack – it’s basically white rice stuffed with meat and vegetables and rolled on dried seaweed.\r\n\r\nYes, it looks like Maki sushi rolls from Japan, but the taste is totally different than the Japanese Maki. For one, all the ingredients in Kimbap are fully cooked. There is also a hint of sesame oil in the ingredients, making the taste stronger than Japanese Sushi rolls. And it’s delicious, of course.', 'seoul_food2.jpg');
INSERT INTO `travel` (`id`, `Country`, `City`, `Label`, `Content`, `image_file`) VALUES
(64, 'South Korea', 'Seoul', 'Places', 'Bukchon Hanok Traditional Village\r\n\r\nFor a taste of Korean traditional culture and architecture, a visit to the Bukchon Hanok Village is a fun and educational way to spend an afternoon. This preserved district of several ancient neighborhoods gives you a feel for what it was like to live in Korea 600 years ago. It\'s right in central Seoul, in the area between the Gyeongbokgung Palace and the Changdeokgung Palace.\r\n\r\nThe neighborhoods of narrow streets feature hanoks or traditional Korean houses. It\'s a unique place, as it\'s a historic area, very popular with tourists, but it\'s also a real neighborhood because the houses are all occupied.', 'seoul_places1.jpg'),
(65, 'South Korea', 'Seoul', 'Places', 'Gyeongbokgung Palace\r\n\r\nFirst built in 1395, Gyeongbokgung Palace is the largest of Seoul\'s five grand palaces built during the powerful Joseon dynasty. Destroyed and rebuilt several times over the centuries, it was restored to its original glory after the Second World War and totally restored in the 1990s.\r\n\r\nA visit to the Gyeongbokgung Palace is one of the best things to do in Seoul because within the palace grounds, you can also find the National Palace Museum of Korea and the National Folk Museum of Korea, and both are worth a visit. The palace museum is especially fascinating as it presents items from the palaces of the Joseon Dynasty.', 'seoul_places2.jpg'),
(66, 'South Korea', 'Seoul', 'Suggestion', 'Leave Your Chopsticks Stuck in Rice\r\n\r\nWe know that this sounds odd because you’ve probably heard about this. Chopsticks that are placed upright resembles the incense burnt at funerals and it is also said to bring bad luck.\r\n\r\nBringing up death at the dinner table is definitely not a good idea.\r\n', 'seoul_suggest.jpg');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `id` int(10) NOT NULL,
  `firstname` varchar(255) NOT NULL,
  `lastname` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password` varchar(255) NOT NULL,
  `urole` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`id`, `firstname`, `lastname`, `email`, `password`, `urole`, `created_at`) VALUES
(1, 'User', 'Test', 'user123@gmail.com', '$2y$10$JJHsGtSjgOth7HN7G2j.c.quhQMjGmzji6qdJPFRlkUVJXF0dNsNS', 'user', '2023-05-26 18:40:45'),
(2, 'Admin', 'Test', 'admin123@gmail.com', '$2y$10$y5Zi9LK6z55DwVg7FWTjwObnOtbC2BpH/xyXv7qBa.rqrq7WbjwG6', 'admin', '2023-05-26 18:41:13');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `review`
--
ALTER TABLE `review`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `travel`
--
ALTER TABLE `travel`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `review`
--
ALTER TABLE `review`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `travel`
--
ALTER TABLE `travel`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=68;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
